# Build and relese the website
name: CI

# Controls when the workflow will activate
on:
  push:
    branches: [ "main" ]

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - uses: actions/setup-node@v4
        name: setup node
        with:
          node-version: 18

      - name: build
        run: |
          cd src
          npm ci
          npm run build
          cd ..
          rsync -avh --delete ./src/dist/ ./docs/
        continue-on-error: true

      - name: Set Git user identity
        run: |
          git config --global user.email "cibot@vitrua.top"
          git config --global user.name "[cibot]"

      - name: Check if gh-pages branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet "refs/heads/gh-pages"; then
            echo "Branch exists"
            echo "::set-output name=branch_exists::true"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_exists::false"
          fi

      - name: Add all modifications
        run: git add docs/

      - name: Commit changes
        run: git commit -m "Update website"  

      - name: Force push to gh-pages branch
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: git push origin HEAD:gh-pages --force
